### ISSUE TITLE
Tag de <collab> com contrib-id-type="orcid"

### ISSUE THREAD

**Issue by odiliohilariomoreirajunior** [scieloorg/sps-docs#31]
Descrição do problema

Temos um artigo de autoria coorporativa que possui número de ORCID, para efetuar a publicação seguindo os critérios SciELO a marcação do ORCID deve ser realizada,  sendo necessário inserir na validação do XC a estrutura de XML abaixo:

```
<contrib-group>
				<contrib contrib-type="author">
					<contrib-id contrib-id-type="orcid">0000-0002-7292-7759</contrib-id>
					<collab>Grupo Temático Trabalho e Educação na Saúde da Associação Brasileira de
						Saúde Coletiva (Abrasco)</collab>
					<xref ref-type="aff" rid="aff1">
						<sup>a</sup>
					</xref>
					<role>responsável por todas as etapas relacionadas à elaboração deste
						manuscrito</role>
				</contrib>
				<aff id="aff1">
					<label>a</label>
					<institution content-type="original">Grupo Temático Trabalho e Educação na Saúde
						da Associação Brasileira de Saúde Coletiva. Rio de Janeiro, RJ, Brasil.
						E-mail: gtabrascogte@gmail.com</institution>
					<institution content-type="orgdiv1">Grupo Temático Trabalho e Educação na
						Saúde</institution>
					<institution content-type="orgname">Associação Brasileira de Saúde
						Coletiva</institution>
					<addr-line>
						<city>Rio de Janeiro</city>
						<state>RJ</state>
					</addr-line>
					<country country="BR">Brasil</country>
					<email>gtabrascogte@gmail.com</email>
				</aff>
			</contrib-group>
```

### Critérios de aceitação

[https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/collab.html]

### Anexos

Envio anexo o [1984-0470-sausoc-32-s2-e230497pt.zip](https://github.com/scieloorg/sps-docs/files/13876686/1984-0470-sausoc-32-s2-e230497pt.zip) para verificação

**Comment by robertatakenaka** [comment]
@odiliohilariomoreirajunior https://orcid.org/0000-0002-0007-7759 pertence a Yonglun Luo. Não estou convencida de que a JATS (https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/collab.html) aceite orcid para collab. A definição de orcid é para autor pessoa.


> ORCID fornece um registro de identificadores exclusivos para pesquisadores e acadêmicos que é aberto, não proprietário, transparente e móvel. ORCID convida todos os pesquisadores a participar sem taxas de inscrição ou custos de manutenção.
> 
> ORCID reconhece que, acima de tudo, os indivíduos são donos de seus registros. Um princípio central do ORCID iniciativa é que os pesquisadores controlem as configurações de privacidade definidas por eles próprios ORCID dados de registro. Os detentores de registros individuais podem controlar quais informações são exibidas publicamente, o que é compartilhado com parceiros de confiança e quem são esses parceiros de confiança.
> 

Fonte: https://info.orcid.org/pt/documenta%C3%A7%C3%A3o/caracter%C3%ADsticas/orcid-registro-a/#:~:text=ORCID%20fornece%20um%20registro%20de,inscri%C3%A7%C3%A3o%20ou%20custos%20de%20manuten%C3%A7%C3%A3o.

**Comment by odiliohilariomoreirajunior** [comment]
@robertatakenaka A Avaliação foi questionada referente ao ORCID coorporativo presente no artigo e a Denise falou que devemos seguir com a publicação.

**Comment by RPostalli** [comment]
@robertatakenaka ticket inválido. Será fechado.
